ajax/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^validar-usuario/$', views.validar_usuario, name='validar_usuario'),
    url(r'^cadastrar-usuario/$', views.cadastrar_usuario, name='cadastrar_usuario'),
    url(r'^cadastrar-receita/$', views.cadastrar_receita, name='cadastrar_receita'),
    url(r'^cadastrar-multiplos/$', views.cadastrar_multiplos, name='cadastrar_multiplos'),
    url(r'^upload-imagens/(?P<pk>\d+)$', views.upload_imagens, name='upload_imagens'),
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cadastrar-usuario/$', views.cadastrar_usuario, name='cadastrar_usuario'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^receita/(?P<pk>\d+)$', views.detalhes_receita, name='detalhes_receita'),
    url(r'^imprimir/(?P<pk>\d+)$', views.imprimir_receita, name='views.imprimir_receita'),
    url(r'^cadastrar-receita/$', views.cadastrar_receita, name='cadastrar_receita'),
    url(r'^categoria/(?P<string>[\w\- ]+)/$', views.categoria_receita, name='categoria_receita'),
    url(r'^pesquisa/$', views.pesquisar, name='pesquisar'),
    url(r'^mapa/$', views.mapa_site, name='mapa_site'),
    url(r'^licencas/$', views.licencas, name='licencas'),
    url(r'^teste/$', views.teste, name='teste'),
    url(r'^$', views.index, name='index'),
]

nerdaldente/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^ajax/', include('ajax.urls', namespace='ajax')),
    url(r'^json/', include('rest.urls', namespace='rest')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import os
import uuid

# Create your models here.

class Usuario(models.Model):
    dj_usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=50)
    data_nascimento = models.DateField()
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=2)
    telefone = models.CharField(max_length=15)

    def __str__(self):
        return self.nome_completo + ' (' + self.dj_usuario.username + ')'

class Categoria(models.Model):
    nome_categoria = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nome_categoria

class ReceitaCategoria(models.Model):
     receita = models.ForeignKey('Receita', on_delete=models.CASCADE)
     categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)

     def __str__(self):
         return self.receita.nome_receita + ' (' + self.receita.autor.dj_usuario.username + ') faz parte da categoria de ' + self.categoria.nome_categoria

class MetodoCozimento(models.Model):
    nome_metodo = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nome_metodo

class Unidade(models.Model):
    nome_unidade = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nome_unidade

class Ingrediente(models.Model):
    nome_ingrediente = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nome_ingrediente

class ReceitaIngrediente(models.Model):
     receita = models.ForeignKey('Receita', on_delete=models.CASCADE)
     ingrediente = models.ForeignKey('Ingrediente', on_delete=models.CASCADE)
     quantidade = models.DecimalField(max_digits=10, decimal_places=1, default=0)
     unidade = models.ForeignKey('Unidade', on_delete=models.CASCADE)

     def __str__(self):
         return self.receita.nome_receita + ' (' + self.receita.autor.dj_usuario.username + ') tem ' + self.ingrediente.nome_ingrediente

class Receita(models.Model):
    autor = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    nome_receita = models.CharField(max_length=50, null=True)
    descricao = models.TextField(max_length=300, null=True)
    tempo_preparo = models.IntegerField(null=True)
    instrucoes_preparo = models.TextField(max_length=800, null=True)
    porcoes = models.IntegerField(null=True)
    valor_nutricional = models.IntegerField(null=True)
    metodo_cozimento = models.ForeignKey('MetodoCozimento', on_delete=models.CASCADE, null=True)
    categorias = models.ManyToManyField('Categoria', through='ReceitaCategoria')
    ingredientes = models.ManyToManyField('Ingrediente', through='ReceitaIngrediente')
    data_publicacao = models.DateTimeField(auto_now_add=True)
    imagem_padrao = models.ForeignKey('Imagem', related_name='+', on_delete=models.CASCADE, blank=True, null=True)
    media_notas = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    qtd_votos = models.IntegerField(default=0)

    def __str__(self):
        return str(self.nome_receita) + ' (' + str(self.autor.dj_usuario.username) + ')'

def update_filename(instance, filename):
    '''
        Atualiza o nome do arquivo enviado com um nome único.
    '''
    path = "uploads/img/"
    name, extension = os.path.splitext(filename)
    format = str(instance.receita.id) + '-' + str(uuid.uuid4()) + extension
    return os.path.join(path, format)

class Imagem(models.Model):
    file = models.ImageField(upload_to=update_filename)
    imagem_alt = models.CharField(max_length=256)
    receita = models.ForeignKey('Receita', on_delete=models.CASCADE)

    def __str__(self):
        return '"' + str(self.file) + '" de ' + self.receita.nome_receita + ' (' + self.receita.autor.dj_usuario.username + ')'

class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    nota = models.IntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(0)]
    )
    receita = models.ForeignKey('Receita', on_delete=models.CASCADE)
    data_publicacao = models.DateTimeField(auto_now_add=True)
    comentario = models.TextField(max_length=300)

    def __str__(self):
        return 'Comentário de ' + self.autor.username + ' para a receita ' + self.receita.nome_receita + ' (' + self.receita.autor.dj_usuario.username + ')'

core/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseServerError
from .models import *
import random, datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db.models import Count
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.db.models import Count, Avg
from django.utils import timezone

# Create your views here.

def get_receitas(query="", source="index"):
    '''
        Método auxiliar para obtenção de uma lista de receitas em vários contextos da aplicação.
    '''
    if source == "index":
        receitas = Receita.objects.exclude(imagem_padrao__isnull=True).filter(categorias=query).order_by('-data_publicacao')[:3]
        if len(receitas) < 3:
            return None
        return receitas
    elif source == "cat":
        receitas = Receita.objects.exclude(imagem_padrao__isnull=True).filter(categorias=query).order_by('-data_publicacao')[:10]
        return receitas
    elif source == "search":
        receitas = Receita.objects.exclude(imagem_padrao__isnull=True).filter(Q(autor__nome_completo__icontains=query) | Q(nome_receita__icontains=query) | Q(descricao__icontains=query) | Q(instrucoes_preparo__icontains=query) | Q(metodo_cozimento__nome_metodo__icontains=query) | Q(categorias__nome_categoria__icontains=query) | Q(ingredientes__nome_ingrediente__icontains=query)).distinct().order_by('-data_publicacao')[:10]
        return receitas
    elif source == "best_small":
        receitas = Receita.objects.exclude(imagem_padrao__isnull=True).order_by('-media_notas')[:10]
        return receitas
    elif source == "best_big":
        receitas = Receita.objects.exclude(imagem_padrao__isnull=True).order_by('-media_notas')[:5]
        return receitas
    elif source == "recent":
        receitas = Receita.objects.exclude(imagem_padrao__isnull=True).order_by('-data_publicacao')[:5]
        return receitas
    elif source == "suggestions":
        receitas = Receita.objects.exclude(imagem_padrao__isnull=True).values('nome_receita').distinct().order_by('-media_notas', '-data_publicacao')[:30]
        return receitas
    else:
        return None

def get_usuarios(type):
    '''
        Obter os usuários mais ativos no site para as listas na página inicial.
    '''
    if type == "degustadores":
        usuarios = Comentario.objects.exclude(receita__imagem_padrao__isnull=True).values('autor__first_name', 'autor__last_name').annotate(total=Count('autor')).order_by('-total')[:5]
        return usuarios
    elif type == "chefs":
        usuarios = Receita.objects.exclude(imagem_padrao__isnull=True).values('autor__dj_usuario__first_name', 'autor__dj_usuario__last_name').annotate(total=Count('autor')).order_by('-total')[:5]
        return usuarios
    return None

# Páginas HTML
def index(request):
    '''
        Cria a página inicial com todos os dados necessários.
    '''

    # Exclui as receitas que expiraram e não foram concluídas.
    Receita.objects.exclude(imagem_padrao__isnull=False).filter(data_publicacao__lte=timezone.now() - datetime.timedelta(minutes=1440)).delete()

    categorias = Categoria.objects.all()
    vet = random.sample(range(0, Categoria.objects.count()), 4)
    data = {
        "categoria1": categorias[vet[0]],
        "receitas1": get_receitas(categorias[vet[0]]),
        "categoria2": categorias[vet[1]],
        "receitas2": get_receitas(categorias[vet[1]]),
        "categoria3": categorias[vet[2]],
        "receitas3": get_receitas(categorias[vet[2]]),
        "categoria4": categorias[vet[3]],
        "receitas4": get_receitas(categorias[vet[3]]),
        "sugestao_receitas": get_receitas(source="suggestions"),
        "chefs": get_usuarios("chefs"),
        "degustadores": get_usuarios("degustadores"),
    }
    return render(request, 'index.html', data)

def login_view(request):
    '''
        Cria o formulário de login e recebe as credenciais enviadas.
    '''
    if request.method == 'POST':
        usuario = authenticate(username=request.POST['email'], password=request.POST['senha'])
        if usuario is not None:
            login(request, usuario)
            if request.POST['next']:
                return redirect(request.POST['next'] + '?from=/login/')
            return redirect('/?ln=ok')
        else:
            return redirect('/login/?ln=fail')
    data = {
        "sugestao_receitas": get_receitas(source="suggestions"),
    }
    return render(request, 'login.html', data)

def logout_view(request):
    '''
        Finaliza a sessão.
    '''
    logout(request)
    return redirect('/?lo=ok')

def detalhes_receita(request, pk):
    '''
        Cria a página com todos os detalhes de uma receita, incluindo suas imagens e comentários recebidos.
    '''
    try:
        receita = Receita.objects.exclude(imagem_padrao__isnull=True).get(id=pk)
    except Receita.DoesNotExist:
        raise Http404

    imagens = Imagem.objects.filter(receita=receita)
    comentarios = Comentario.objects.filter(receita=receita)
    data = {
        'id_receita': pk,
        'url': "https://nerdaldente.com.br/receita/" + pk,
        'receita': receita,
        'autor': receita.autor.nome_completo.title(),
        'imagens': imagens,
        'comentarios': comentarios,
        "sugestao_receitas": get_receitas(source="suggestions"),
        }

    if request.method == 'POST':
        try:
            autor = User.objects.get(id=request.user.id)
        except User.DoesNotExist:
            raise PermissionDenied

        try:
            receita = Receita.objects.get(id=pk)
        except Receita.DoesNotExist:
            raise PermissionDenied

        try:
            nota = request.POST['nota']
        except KeyError:
            return JsonResponse(JSend.fail({"nota": "Campo requerido."}))

        try:
            comentario = request.POST['comentario']
        except KeyError:
            return JsonResponse(JSend.fail({"comentario": "Campo requerido."}))

        comentario = Comentario(autor=autor, nota=nota, receita=receita, comentario=comentario)
        comentario.save()

        media_notas = Comentario.objects.filter(receita=receita).exclude(nota=0).aggregate(Avg('nota'))
        qtd_votos = Comentario.objects.filter(receita=receita).exclude(nota=0).aggregate(Count('nota'))

        receita.media_notas = float(media_notas["nota__avg"])
        receita.qtd_votos = qtd_votos["nota__count"]
        receita.save()

    return render(request, 'detalhes.html', data)

def imprimir_receita(request, pk):
    '''
        Cria a página para ser impressa com os detalhes mais relevantes de uma receita.
    '''

    try:
        receita = Receita.objects.exclude(imagem_padrao__isnull=True).get(id=pk)
    except Receita.DoesNotExist:
        raise Http404
    data = {
        'id_receita': pk,
        'url': "https://nerdaldente.com.br/imprimir/" + pk,
        'receita': receita,
        'autor': receita.autor.nome_completo.title(),
        }
    return render(request, 'imprimir.html', data)

def categoria_receita(request, string):
    '''
        Lista as receitas mais recentes de uma categoria.
    '''

    try:
        categoria = Categoria.objects.get(nome_categoria=string.title())
    except Categoria.DoesNotExist:
        raise Http404
    data = {
        'categoria': string.title(),
        'url': "https://nerdaldente.com.br/categoria/" + string,
        'receitas': get_receitas(categoria, "cat"),
        'receitas_aside': get_receitas(source="best_big"),
        "sugestao_receitas": get_receitas(source="suggestions"),
    }
    return render(request, 'listar_categoria.html', data)

def pesquisar(request):
    '''
        Lista as receitas que se adequam à string de pesquisa do usuário.
    '''

    if request.GET.get('q'):
        q = str(request.GET.get('q')).lower()
    else:
        return render(request, 'teste.html')
    data = {
        'q': q,
        'url': "https://nerdaldente.com.br/pesquisar/" + q,
        'receitas': get_receitas(q, "search"),
        'receitas_aside': get_receitas(source="best_big"),
        "sugestao_receitas": get_receitas(source="suggestions"),
        }
    return render(request, 'listar_pesquisa.html', data)

def cadastrar_usuario(request):
    '''
        Cria um formulário para o cadastro de um novo usuário.
    '''
    data = {
        "sugestao_receitas": get_receitas(source="suggestions"),
    }
    return render(request, 'cadastro_usuario.html', data)

@login_required
def cadastrar_receita(request):
    '''
        Cria um formulário para o cadastro de uma nova receita.
    '''

    try:
        usuario = Usuario.objects.get(dj_usuario=request.user.id)
    except Usuario.DoesNotExist:
        return HttpResponseServerError()

    nova_receita = Receita(autor=usuario)
    nova_receita.save()
    data = {
    "receitas_aside": get_receitas(source="recent"),
    "sugestao_receitas": get_receitas(source="suggestions"),
    "receita_id": nova_receita.id,
    'autor': usuario.nome_completo.title(),
    }
    return render(request, 'cadastro_receita.html', data)

def mapa_site(request):
    '''
        Cria uma página com as URLs mais relevantes da aplicação.
    '''

    data = {
    "sugestao_receitas": get_receitas(source="suggestions"),
    'receitas_aside': get_receitas(source="best_small"),
    }
    return render(request, 'mapa_site.html', data)

def licencas(request):
    '''
        Cria uma página com atribuindo autoria aos componentes de software utilizados.
    '''

    data = {
    "sugestao_receitas": get_receitas(source="suggestions"),
    }
    return render(request, 'licencas.html')

def teste(request):
    '''
        Um easter egg.
    '''
    return render(request, 'teste.html')

core/templates/detalhes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<title>{{ receita.nome_receita }} – Nerd al Dente</title>
		<meta property="og:url" content={{ url }}>
		<meta property="og:title" content="{{ receita.nome_receita }} – Nerd al Dente">
		{% include 'includes/meta.html' %}
		<link rel="stylesheet" href="{% static '/plugins/css/font-awesome.min.css' %}">
	</head>
	<body>
		<div class="wrap">

				{% include 'includes/header.html' %}

				{% include 'includes/menu.html' %}

				<div itemscope itemtype="http://schema.org/Recipe">
				<div class="container">
					<div class="alert alert-success alert-dismissible hidden" role="alert" id="aviso"></div>

					<span id="nota" class="hidden">{{ receita.media_notas }}</span>
					<span id="url_receita" class="hidden">{{ url }}</span>
					<span id="url_img" class="hidden">https://nerdaldente.com.br/{{ receita.imagem_padrao.file }}</span>
					<span id="id_receita" class="hidden">{{ id_receita }}</span>

					<section>
						<div class="row">
							<div class="col-md-12">
								<div class="bg-overlay text-center">
									<h1><span itemprop="name" id="nome_receita">{{ receita.nome_receita }}</span></h1>
									<p><i class="fa fa-clock-o" aria-hidden="true"></i> <span itemprop="prepTime" id="tempo_preparo">{{ receita.tempo_preparo }}</span> Minuto(s)</p>
									<p><i class="fa fa-cutlery" aria-hidden="true"></i> <span itemprop="recipeYield" id="porcoes">{{ receita.porcoes }}</span> Porção(ões)</p>
									<p itemprop="nutrition" itemscope itemtype="http://schema.org/NutritionInformation"><i class="fa fa-pie-chart" aria-hidden="true"></i> <span itemprop="calories" id="calorias">{{ receita.valor_nutricional }}</span> Caloria(s)</p>
									<p><i class="fa fa-cube" aria-hidden="true"></i> Tipo de Cozimento | <span itemprop="cookingMethod" id="metodo">{{ receita.metodo_cozimento }}</span></p>
									<p id="categorias"><i class="fa fa-tags" aria-hidden="true"></i>
										{% for categoria in receita.categorias.all %}
	    							{% if forloop.first %}{% else %}
	        					{% if forloop.last %} e {% else %}, {% endif %}
	    							{% endif %}<span itemprop="recipeCategory" id="categoria{{ forloop.counter }}">{{categoria}}</span>
										{% empty %}
										<span>Não há categorias registradas</span>
										{% endfor %}
									</p>
								</div>
							</div>
						</div>
					</section>
					<main>
						<br>
						<div class="row">
							<div class="col-md-8">
								<p>Receita enviada por <span itemprop="author" id="autor">{{ autor }}</span> em <span itemprop="datePublished">{{ receita.data_publicacao }}</span>.</p>
								<h2>Ingredientes</h2>
								<ul id="ingredientes">
									{% for ingrediente in receita.receitaingrediente_set.all %}
									<li><span itemprop="recipeIngredient" id="ingrediente{{ forloop.counter }}">{{ ingrediente.quantidade }} {{ ingrediente.unidade.nome_unidade }} de {{ ingrediente.ingrediente.nome_ingrediente }}</li>
									{% empty %}
									<li>Não há ingredientes registrados.</li>
									{% endfor %}
								</ul>

								<h2>Instruções</h2>
								<p><span itemprop="description" id="descricao" style="white-space: pre-wrap;">{{ receita.descricao }}</span></p>
								<br>
								<p><span itemprop="recipeInstructions" id="instrucoes" style="white-space: pre-wrap;">{{ receita.instrucoes_preparo }}</span></p>
							</div>

							<div class="col-md-4">
								<div id="myCarousel" class="carousel slide fotos" data-ride="carousel">
									<ol class="carousel-indicators">
										{% for imagem in imagens %}
										{% if forloop.first %}
										<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
										{% else %}
							  		<li data-target="#myCarousel" data-slide-to="{{ forloop.counter }}"></li>
										{% endif %}
										{% endfor %}
									</ol>

									<div class="carousel-inner">
										{% for imagem in imagens %}
										{% if forloop.first %}
										<div class="item active">
											<img src="/media/{{ imagem.file }}" alt="{{ imagem.imagem_alt }}" style="height: 250px; width:100%;">
							  		</div>
										{% else %}
										<div class="item">
											<img src="/media/{{ imagem.file }}" alt="{{ imagem.imagem_alt }}" style="height: 250px; width:100%;">
							  		</div>
										{% endif %}
										{% endfor %}
									</div>

									<a class="left carousel-control" href="#myCarousel" data-slide="prev">
							  		<span class="glyphicon glyphicon-chevron-left"></span>
							  		<span class="sr-only">Anterior</span>
									</a>
									<a class="right carousel-control" href="#myCarousel" data-slide="next">
							  		<span class="glyphicon glyphicon-chevron-right"></span>
							  		<span class="sr-only">Próximo</span>
									</a>
						  	</div>
						  	<br><br>
						  	<center>
									<a class="btn btn-default" href="/imprimir/{{ id_receita }}" target="_blank"><i class="fa fa-print" aria-hidden="true"></i> Imprimir receita</a>
								</center>
						  	<br>
						  	<center>
									<a class="btn btn-default" id="exportar"><i class="fa fa-share-square-o" aria-hidden="true"></i> Exportar receita</a>
								</center>
							</div>
						</main>
					</div>
			</div>
				<section>
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<h3>Comentários</h3>
							</div>
						</div>
					{% for comentario in comentarios %}
					<div class="row">
						<div class="col-md-1">
							<div class="thumb">
								<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
							</div>
						</div>

						<div class="col-md-5">
							<div class="panel panel-default">
								<div class="panel-heading">
									<strong>{{ comentario.autor.first_name }} {{ comentario.autor.last_name }}</strong> <span class="text-muted">comentou em {{ comentario.data_publicacao }}</span>
								</div>
								<div class="panel-body">
									<span itemprop="comment" id="comentario{{ forloop.counter }}">{{ comentario.comentario }}</span>
								</div>
							</div>
						</div>

						<div class="col-md-6"></div>
					</div>
					{% empty %}
					<div class="row">
						<div class="col-md-6">
						 <div class="well"><h4><span class="glyphicon glyphicon-comment" aria-hidden="true"></span></h4>
						 <p>Ninguém comentou ainda. Que tal ser o primeiro?</p></div>
					 </div>
				 </div>
					{% endfor %}

					{% if user.is_authenticated %}
					<div class="row">
						<div class="col-md-6">
							<h3>Junte-se à conversa</h3>
							<div class="panel panel-default">
								<div class="panel-body">
								<form method="POST" action="/receita/{{ id_receita }}">{% csrf_token %}
									<div class="form-group">
									<label class="sr-only" for="id_comentario">Comentário:</label>
									<textarea id="id_comentario" name="comentario" cols="60" rows="5" maxlength="300" placeholder="Escreva seu comentário..." required></textarea>
									<br><small id="inputComentarioHelp" class="form-text text-muted"><span id=inputComentarioRestantes>300</span> caracteres restantes.</small>
								</div>
									<label for="id_nota">Você gostou dessa receita?</label>
									<input type="hidden" name="nota" required id="id_nota" value="0"/>
									<div class="lead panel-body">
										<label class="sr-only" for="hearts">Atribua uma nota.</label>
										<div id="hearts" class="starrr"></div>
									</div>
									<button class="btn btn-success" type="submit">Publicar seu comentário</button>
								</form>
							</div>
						</div>
						</div>
							</div>
					{% else %}
						<div class="row">
							<a class="btn btn-success" href="/login?next=/receita/{{ id_receita }}" role="button">Faça login para deixar sua opinião!</a>
							<br><br>
						</div>
					{% endif %}
				</div>
				</section>
			</div>
		</div>

		{% include 'includes/footer.html' %}

		{% include 'includes/scripts.html' %}
		<script src="{% static 'js/detalhes.js' %}"></script>
		<script src="{% static 'js/util.js' %}"></script>
		<script src="{% static 'plugins/js/starrr.js' %}"></script>

	</body>
</html>

core/templates/imprimir.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<title>{{ receita.nome_receita }} – Nerd al Dente</title>
		<link rel="icon" type="image/png" href="{% static 'img/logo16.png' %}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static '/plugins/css/font-awesome.min.css' %}">
	</head>
	<body onload="imprimir()">
		<main class="container">
			<div itemscope itemtype="http://schema.org/Recipe">
				<div class="row">
					<div class="col-md-12">
						<div class="row">
							<center>
								<img src="/media/{{ receita.imagem_padrao.file }}">
							</center>
						</div>
						<br>
						<div class="text-center">
							<h1><strong><span itemprop="name" id="nome_receita">{{ receita.nome_receita }}</span></strong></h1>
							<p>
								<i class="fa fa-clock-o" aria-hidden="true"></i> <span itemprop="prepTime" id="tempo_preparo">{{ receita.tempo_preparo }}</span> Minuto(s)&nbsp;&nbsp;|&nbsp;&nbsp;
								<i class="fa fa-cutlery" aria-hidden="true"></i> <span itemprop="recipeYield" id="porcoes">{{ receita.porcoes }}</span> Porção(ões)&nbsp;&nbsp;|&nbsp;&nbsp;
								<span itemprop="nutrition" itemscope itemtype="http://schema.org/NutritionInformation"><i class="fa fa-pie-chart" aria-hidden="true"></i> <span itemprop="calories" id="calorias">{{ receita.valor_nutricional }}</span> Caloria(s)</span>&nbsp;&nbsp;|&nbsp;&nbsp;
								<i class="fa fa-cube" aria-hidden="true"></i> Tipo de Cozimento: <span itemprop="cookingMethod" id="metodo">{{ receita.metodo_cozimento }}</span>&nbsp;&nbsp;|&nbsp;&nbsp;
								<i class="fa fa-tags" aria-hidden="true"></i>
								{% for categoria in receita.categorias.all %}
								{% if forloop.first %}{% else %}
								{% if forloop.last %} e {% else %}, {% endif %}
								{% endif %}<span itemprop="recipeCategory" id="categoria{{ forloop.counter }}">{{categoria}}</span>
								{% empty %}
								<span>Não há categorias registradas</span>
								{% endfor %}
							</p>
						</div>
					</div>
				</div>
				<br>
				<hr/>
				<div class="row">
					<h2>Ingredientes</h2>
					<ul id="ingredientes">
						{% for ingrediente in receita.receitaingrediente_set.all %}
						<li><span itemprop="recipeIngredient" id="ingrediente{{ forloop.counter }}">{{ ingrediente.quantidade }} {{ ingrediente.unidade.nome_unidade }} de {{ ingrediente.ingrediente.nome_ingrediente }}</li>
						{% empty %}
						<li>Não há ingredientes registrados.</li>
						{% endfor %}
					</ul>

					<h2>Instruções</h2>
					<p><span itemprop="description" id="descricao" style="white-space: pre-wrap;">{{ receita.descricao }}</span></p>
					<br>
					<p><span itemprop="recipeInstructions" id="instrucoes" style="white-space: pre-wrap;">{{ receita.instrucoes_preparo }}</span></p>
					<br>
				</div>
				<hr/>
			</div>
		</main>
		<footer class="container">
    		<p>© 2017. Receita publicada no <strong>Nerd al Dente</strong> por <span itemprop="author" id="autor">{{ autor }}</span>. Todos os direitos reservados.</p>
		</footer>

		<script>
		function imprimir() {
			window.print();
		}
		</script>

	</body>
</html>